// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int countAboveHalf = 0, countBelowHalf = 0;
		// The program generates random numbers N times
		for (int count =0 ; count < N; count++) {
			if (Math.random() > 0.5) {
				countAboveHalf ++;
			} else {
				countBelowHalf ++;
			}
		}

		System.out.println(">0.5: " + countAboveHalf + " times");
		System.out.println("<=0.5: " + countBelowHalf  + " times");

		// The program calculates the ratio between the two counts
		// (making sure none of them equals 0 - edge case)
		double ratio;
		double doublecountAbove = countAboveHalf, doublecountBelow = countBelowHalf;
		if (countAboveHalf != 0 && countBelowHalf != 0) {
			if (countAboveHalf > countBelowHalf) {
				ratio = (doublecountBelow / doublecountAbove);
			} else {
				ratio = (doublecountAbove / doublecountBelow);
			}
			System.out.println("ratio: " + ratio);
		}
	}
}
